// AUTOGENERATED by zk/scripts/generate-tally-circuit.ts
// Output: zk/circuits/tally.circom
// Purpose: Results commitment gadget (BV_TALLY_RESULT_COMMIT_V1)
//
// Manifest arity:
// - positions: 15
// - totalCandidates: 30
//
// Candidate counts are provided per position as counts_<i>[] signals,
// plus abstain[] per position.
//
// Public inputs:
//   electionIdHash, electionVoteRoot, manifestHash, resultsHash
//
// Private inputs:
//   abstain[], counts_<i>[]
//
pragma circom 2.1.6;

include "circomlib/poseidon.circom";

template BVTallyResultCommitV1() {
  // Public anchors
  signal input electionIdHash;
  signal input electionVoteRoot;
  signal input manifestHash;
  signal input resultsHash;

  // Private tally vector
  signal input abstain[15];
  signal input counts_0[2];
  signal input counts_1[2];
  signal input counts_2[2];
  signal input counts_3[2];
  signal input counts_4[2];
  signal input counts_5[2];
  signal input counts_6[2];
  signal input counts_7[2];
  signal input counts_8[2];
  signal input counts_9[2];
  signal input counts_10[2];
  signal input counts_11[2];
  signal input counts_12[2];
  signal input counts_13[2];
  signal input counts_14[2];

  // Poseidon fold hash
  component p0 = Poseidon(2);
  p0.inputs[0] <== 123456789;
  p0.inputs[1] <== electionIdHash;

  component p1 = Poseidon(2);
  p1.inputs[0] <== p0.out;
  p1.inputs[1] <== electionVoteRoot;

  component p2 = Poseidon(2);
  p2.inputs[0] <== p1.out;
  p2.inputs[1] <== manifestHash;

  signal h;
  h <== p2.out;

  component p3 = Poseidon(2);
  p3.inputs[0] <== h;
  p3.inputs[1] <== abstain[0];
  h <== p3.out;

  component p4 = Poseidon(2);
  p4.inputs[0] <== h;
  p4.inputs[1] <== counts_0[0];
  h <== p4.out;

  component p5 = Poseidon(2);
  p5.inputs[0] <== h;
  p5.inputs[1] <== counts_0[1];
  h <== p5.out;

  component p6 = Poseidon(2);
  p6.inputs[0] <== h;
  p6.inputs[1] <== abstain[1];
  h <== p6.out;

  component p7 = Poseidon(2);
  p7.inputs[0] <== h;
  p7.inputs[1] <== counts_1[0];
  h <== p7.out;

  component p8 = Poseidon(2);
  p8.inputs[0] <== h;
  p8.inputs[1] <== counts_1[1];
  h <== p8.out;

  component p9 = Poseidon(2);
  p9.inputs[0] <== h;
  p9.inputs[1] <== abstain[2];
  h <== p9.out;

  component p10 = Poseidon(2);
  p10.inputs[0] <== h;
  p10.inputs[1] <== counts_2[0];
  h <== p10.out;

  component p11 = Poseidon(2);
  p11.inputs[0] <== h;
  p11.inputs[1] <== counts_2[1];
  h <== p11.out;

  component p12 = Poseidon(2);
  p12.inputs[0] <== h;
  p12.inputs[1] <== abstain[3];
  h <== p12.out;

  component p13 = Poseidon(2);
  p13.inputs[0] <== h;
  p13.inputs[1] <== counts_3[0];
  h <== p13.out;

  component p14 = Poseidon(2);
  p14.inputs[0] <== h;
  p14.inputs[1] <== counts_3[1];
  h <== p14.out;

  component p15 = Poseidon(2);
  p15.inputs[0] <== h;
  p15.inputs[1] <== abstain[4];
  h <== p15.out;

  component p16 = Poseidon(2);
  p16.inputs[0] <== h;
  p16.inputs[1] <== counts_4[0];
  h <== p16.out;

  component p17 = Poseidon(2);
  p17.inputs[0] <== h;
  p17.inputs[1] <== counts_4[1];
  h <== p17.out;

  component p18 = Poseidon(2);
  p18.inputs[0] <== h;
  p18.inputs[1] <== abstain[5];
  h <== p18.out;

  component p19 = Poseidon(2);
  p19.inputs[0] <== h;
  p19.inputs[1] <== counts_5[0];
  h <== p19.out;

  component p20 = Poseidon(2);
  p20.inputs[0] <== h;
  p20.inputs[1] <== counts_5[1];
  h <== p20.out;

  component p21 = Poseidon(2);
  p21.inputs[0] <== h;
  p21.inputs[1] <== abstain[6];
  h <== p21.out;

  component p22 = Poseidon(2);
  p22.inputs[0] <== h;
  p22.inputs[1] <== counts_6[0];
  h <== p22.out;

  component p23 = Poseidon(2);
  p23.inputs[0] <== h;
  p23.inputs[1] <== counts_6[1];
  h <== p23.out;

  component p24 = Poseidon(2);
  p24.inputs[0] <== h;
  p24.inputs[1] <== abstain[7];
  h <== p24.out;

  component p25 = Poseidon(2);
  p25.inputs[0] <== h;
  p25.inputs[1] <== counts_7[0];
  h <== p25.out;

  component p26 = Poseidon(2);
  p26.inputs[0] <== h;
  p26.inputs[1] <== counts_7[1];
  h <== p26.out;

  component p27 = Poseidon(2);
  p27.inputs[0] <== h;
  p27.inputs[1] <== abstain[8];
  h <== p27.out;

  component p28 = Poseidon(2);
  p28.inputs[0] <== h;
  p28.inputs[1] <== counts_8[0];
  h <== p28.out;

  component p29 = Poseidon(2);
  p29.inputs[0] <== h;
  p29.inputs[1] <== counts_8[1];
  h <== p29.out;

  component p30 = Poseidon(2);
  p30.inputs[0] <== h;
  p30.inputs[1] <== abstain[9];
  h <== p30.out;

  component p31 = Poseidon(2);
  p31.inputs[0] <== h;
  p31.inputs[1] <== counts_9[0];
  h <== p31.out;

  component p32 = Poseidon(2);
  p32.inputs[0] <== h;
  p32.inputs[1] <== counts_9[1];
  h <== p32.out;

  component p33 = Poseidon(2);
  p33.inputs[0] <== h;
  p33.inputs[1] <== abstain[10];
  h <== p33.out;

  component p34 = Poseidon(2);
  p34.inputs[0] <== h;
  p34.inputs[1] <== counts_10[0];
  h <== p34.out;

  component p35 = Poseidon(2);
  p35.inputs[0] <== h;
  p35.inputs[1] <== counts_10[1];
  h <== p35.out;

  component p36 = Poseidon(2);
  p36.inputs[0] <== h;
  p36.inputs[1] <== abstain[11];
  h <== p36.out;

  component p37 = Poseidon(2);
  p37.inputs[0] <== h;
  p37.inputs[1] <== counts_11[0];
  h <== p37.out;

  component p38 = Poseidon(2);
  p38.inputs[0] <== h;
  p38.inputs[1] <== counts_11[1];
  h <== p38.out;

  component p39 = Poseidon(2);
  p39.inputs[0] <== h;
  p39.inputs[1] <== abstain[12];
  h <== p39.out;

  component p40 = Poseidon(2);
  p40.inputs[0] <== h;
  p40.inputs[1] <== counts_12[0];
  h <== p40.out;

  component p41 = Poseidon(2);
  p41.inputs[0] <== h;
  p41.inputs[1] <== counts_12[1];
  h <== p41.out;

  component p42 = Poseidon(2);
  p42.inputs[0] <== h;
  p42.inputs[1] <== abstain[13];
  h <== p42.out;

  component p43 = Poseidon(2);
  p43.inputs[0] <== h;
  p43.inputs[1] <== counts_13[0];
  h <== p43.out;

  component p44 = Poseidon(2);
  p44.inputs[0] <== h;
  p44.inputs[1] <== counts_13[1];
  h <== p44.out;

  component p45 = Poseidon(2);
  p45.inputs[0] <== h;
  p45.inputs[1] <== abstain[14];
  h <== p45.out;

  component p46 = Poseidon(2);
  p46.inputs[0] <== h;
  p46.inputs[1] <== counts_14[0];
  h <== p46.out;

  component p47 = Poseidon(2);
  p47.inputs[0] <== h;
  p47.inputs[1] <== counts_14[1];
  h <== p47.out;

  // Bind to claimed resultsHash
  h === resultsHash;
}

component main = BVTallyResultCommitV1();
