// This file is generated by zk/scripts/generate-tally-circuit.ts
// Run the generator with your manifest JSON to populate this file.
pragma circom 2.1.6;

template Placeholder() {
  signal input x;
  x * 1 === x;
}

component main = Placeholder();
