import { serve } from "std/http/server";
import { createClient } from "@supabase/supabase-js";

import { requireAdmin } from "../_shared/requireAdmin.ts";

type Body = {
  electionId: string; // UUID
};

const corsHeaders: Record<string, string> = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, x-kiosk-id, x-kiosk-secret",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

function json(status: number, payload: Record<string, unknown>) {
  return new Response(JSON.stringify(payload), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}

function envAny(...names: string[]) {
  for (const n of names) {
    const v = Deno.env.get(n);
    if (v) return v;
  }
  return null;
}

function requireEnvAny(...names: string[]) {
  const v = envAny(...names);
  if (!v) throw new Error(`Missing required secret: ${names.join(" OR ")}`);
  return v;
}

async function isAdminCaller(req: Request, supabaseUrl: string, anonKey: string): Promise<false | true | Response> {
  const authHeader = req.headers.get("Authorization") ?? "";
  if (!authHeader) return false;

  const authed = createClient(supabaseUrl, anonKey, {
    global: { headers: { Authorization: authHeader } },
    auth: { persistSession: false },
  });

  const { data: userData, error: userErr } = await authed.auth.getUser();
  if (userErr || !userData?.user) {
    console.error("[generate-tally-circuit] Invalid token", { error: userErr?.message ?? String(userErr) });
    return json(401, { error: "Invalid token" });
  }

  const { data: roleRow, error: roleErr } = await authed
    .from("user_roles")
    .select("role")
    .eq("user_id", userData.user.id)
    .maybeSingle<{ role: string }>();

  if (roleErr) {
    console.error("[generate-tally-circuit] Role lookup failed", { error: roleErr.message });
    return json(500, { error: "Failed to validate admin role" });
  }

  return roleRow?.role === "admin";
}

function requireKioskSecret(req: Request) {
  const expected = requireEnvAny("KIOSK_SECRET", "KIOSK_RECEIPT_SECRET");
  const got = req.headers.get("x-kiosk-secret") || "";
  if (!got || got !== expected) {
    return json(401, { error: "Unauthorized" });
  }
  return null;
}

function isUuid(v: string) {
  return /^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/.test(v);
}

type ManifestRow = {
  election_id: string;
  spec_version: string;
  manifest_hash: string;
  manifest: unknown;
};

type ManifestPosition =
  | string
  | {
      name?: string;
      position?: string;
      candidates?: unknown[];
    };

type Manifest = {
  spec_version?: string;
  positions?: ManifestPosition[];
  manifest?: {
    positions?: ManifestPosition[];
    spec_version?: string;
  };
};

function normalizePositions(manifestRaw: Manifest): { name: string; candidateCount: number }[] {
  const inner = (manifestRaw.manifest ?? manifestRaw) as Manifest;
  const positions = inner.positions ?? [];
  if (!Array.isArray(positions) || positions.length === 0) {
    throw new Error("Manifest missing positions[]");
  }

  return positions.map((p, idx) => {
    if (typeof p === "string") return { name: p, candidateCount: 0 };
    const name = (p.name ?? p.position ?? `Position_${idx}`) as string;
    const candidateCount = Array.isArray(p.candidates) ? p.candidates.length : 0;
    return { name, candidateCount };
  });
}

function emitCircom(meta: { positions: { name: string; candidateCount: number }[] }) {
  const posCount = meta.positions.length;
  const candCountsPerPos = meta.positions.map((p) => p.candidateCount);
  const totalCandidates = candCountsPerPos.reduce((a, b) => a + b, 0);

  const domainConst = "123456789"; // BV_TALLY_RESULT_COMMIT_V1

  const header = `// AUTOGENERATED by supabase/functions/generate-tally-circuit\n// Purpose: Results commitment gadget (BV_TALLY_RESULT_COMMIT_V1)\n//\n// Manifest arity:\n// - positions: ${posCount}\n// - totalCandidates: ${totalCandidates}\n//\n// Public inputs:\n//   electionIdHash, electionVoteRoot, manifestHash, resultsHash\n//\npragma circom 2.1.6;\n\ninclude \"circomlib/poseidon.circom\";\n\ntemplate BVTallyResultCommitV1() {\n  signal input electionIdHash;\n  signal input electionVoteRoot;\n  signal input manifestHash;\n  signal input resultsHash;\n\n  signal input abstain[${posCount}];\n`;

  let countsDecl = "";
  for (let i = 0; i < posCount; i++) {
    countsDecl += `  signal input counts_${i}[${candCountsPerPos[i]}];\n`;
  }

  const hashInit = `\n  component p0 = Poseidon(2);\n  p0.inputs[0] <== ${domainConst};\n  p0.inputs[1] <== electionIdHash;\n\n  component p1 = Poseidon(2);\n  p1.inputs[0] <== p0.out;\n  p1.inputs[1] <== electionVoteRoot;\n\n  component p2 = Poseidon(2);\n  p2.inputs[0] <== p1.out;\n  p2.inputs[1] <== manifestHash;\n\n  signal h;\n  h <== p2.out;\n`;

  let fold = "";
  let poseIdx = 3;
  for (let i = 0; i < posCount; i++) {
    fold += `\n  component p${poseIdx} = Poseidon(2);\n  p${poseIdx}.inputs[0] <== h;\n  p${poseIdx}.inputs[1] <== abstain[${i}];\n  h <== p${poseIdx}.out;\n`;
    poseIdx++;

    for (let j = 0; j < candCountsPerPos[i]; j++) {
      fold += `\n  component p${poseIdx} = Poseidon(2);\n  p${poseIdx}.inputs[0] <== h;\n  p${poseIdx}.inputs[1] <== counts_${i}[${j}];\n  h <== p${poseIdx}.out;\n`;
      poseIdx++;
    }
  }

  const footer = `\n  h === resultsHash;\n}\n\ncomponent main = BVTallyResultCommitV1();\n`;
  return header + countsDecl + hashInit + fold + footer;
}

serve(async (req: Request) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeaders });
  if (req.method !== "POST") return json(405, { error: "Method not allowed" });

  try {
    const supabaseUrl = requireEnvAny("SUPABASE_URL");
    const anonKey = requireEnvAny("SUPABASE_ANON_KEY", "SUPABASE_ANON_PUBLIC_KEY");
    const serviceRoleKey = requireEnvAny("SUPABASE_SERVICE_ROLE_KEY", "SERVICE_ROLE_KEY");

    try {
      await requireAdmin({ req, supabaseUrl, anonKey, serviceRoleKey });
    } catch (e: any) {
      const status = e?.status ?? 500;
      return json(status, { error: e?.message ?? String(e) });
    }

    // Auth gate: admin JWT OR kiosk secret.
    const adminCheck = await isAdminCaller(req, supabaseUrl, anonKey);
    if (adminCheck instanceof Response) return adminCheck;
    if (!adminCheck) {
      const kioskResp = requireKioskSecret(req);
      if (kioskResp) return kioskResp;
    }

    const body = (await req.json()) as Body;
    if (!body?.electionId || !isUuid(body.electionId)) {
      return json(400, { error: "Invalid electionId" });
    }

    const supabase = createClient(supabaseUrl, serviceRoleKey, {
      auth: { persistSession: false },
    });

    const { data: manifestRow, error: manErr } = await supabase
      .from("election_manifests")
      .select("election_id,spec_version,manifest_hash,manifest")
      .eq("election_id", body.electionId)
      .maybeSingle<ManifestRow>();

    if (manErr) {
      console.error("[generate-tally-circuit] manifest query failed", { error: manErr.message });
      return json(500, { error: "Failed to read manifest" });
    }
    if (!manifestRow) {
      return json(404, { error: "Manifest not found. Generate manifest first." });
    }

    const positions = normalizePositions(manifestRow.manifest as Manifest);
    const meta = {
      specVersion: "BV_TALLY_RESULT_COMMIT_V1",
      electionId: manifestRow.election_id,
      manifestHash: manifestRow.manifest_hash,
      positions,
      generatedAt: new Date().toISOString(),
    };

    const circom = emitCircom({ positions });

    return json(200, {
      status: "ok",
      meta,
      circom,
    });
  } catch (e) {
    console.error("generate-tally-circuit error:", e);
    return json(500, { error: "Unexpected error", details: e instanceof Error ? e.message : String(e) });
  }
});
