#!/usr/bin/env node
/**
 * zk/scripts/generate-tally-circuit.ts
 *
 * Generates zk/circuits/tally.circom from an election manifest.
 *
 * Two modes:
 *  A) From local manifest file (snapshot or raw manifest JSON):
 *     node zk/scripts/generate-tally-circuit.ts --manifestFile zk/manifests/<file>.json
 *
 *  B) From Supabase by electionId (recommended for thesis + deployment):
 *     node zk/scripts/generate-tally-circuit.ts --electionId <uuid>
 *
 *     This will:
 *       - fetch the manifest row from Supabase
 *       - write a reproducible snapshot under zk/manifests/
 *       - generate zk/circuits/tally.circom + tally.meta.json
 *
 * Env (required for mode B):
 *   SUPABASE_URL
 *   SUPABASE_SERVICE_ROLE_KEY
 */

import fs from "node:fs";
import path from "node:path";

import { fetchElectionManifest, writeManifestSnapshot } from "./fetch-manifest";

type ManifestPosition =
  | string
  | {
      name?: string;
      position?: string;
      candidates?: unknown[];
    };

type SnapshotEnvelope = {
  schema?: string;
  election_id?: string;
  spec_version?: string;
  manifest_hash?: string;
  manifest?: unknown;
};

type Manifest = {
  spec_version?: string;
  positions?: ManifestPosition[];
  manifest?: {
    positions?: ManifestPosition[];
    spec_version?: string;
  };
};

function readJson(filePath: string): unknown {
  return JSON.parse(fs.readFileSync(filePath, "utf8"));
}

function normalizePositions(manifestRaw: Manifest): { name: string; candidateCount: number }[] {
  const inner = (manifestRaw.manifest ?? manifestRaw) as Manifest;
  const positions = inner.positions ?? [];
  if (!Array.isArray(positions) || positions.length === 0) {
    throw new Error("Manifest missing positions[]");
  }

  return positions.map((p, idx) => {
    if (typeof p === "string") {
      return { name: p, candidateCount: 0 };
    }
    const name = (p.name ?? p.position ?? `Position_${idx}`) as string;
    const candidateCount = Array.isArray(p.candidates) ? p.candidates.length : 0;
    return { name, candidateCount };
  });
}

/**
 * Poseidon folding hash:
 *   h0 = Poseidon([domain, electionIdHash])
 *   h1 = Poseidon([h0, electionVoteRoot])
 *   h2 = Poseidon([h1, manifestHash])
 *   then fold each abstain/count:
 *     h = Poseidon([h, x])
 *   finally constrain h == resultsHash
 *
 * NOTE (Step 2.5/2.6 scope):
 * - This is the results commitment layer.
 * - Next step will bind the tally vector to the vote-set in-circuit (or via a ZK-friendly root pipeline).
 */
function emitCircom(meta: { positions: { name: string; candidateCount: number }[] }) {
  const posCount = meta.positions.length;
  const candCountsPerPos = meta.positions.map((p) => p.candidateCount);
  const totalCandidates = candCountsPerPos.reduce((a, b) => a + b, 0);

  // Domain separator as a field element constant.
  // Rotate/change this ONLY with a version bump.
  const domainConst = "123456789"; // BV_TALLY_RESULT_COMMIT_V1

  const header = `// AUTOGENERATED by zk/scripts/generate-tally-circuit.ts
// Output: zk/circuits/tally.circom
// Purpose: Results commitment gadget (BV_TALLY_RESULT_COMMIT_V1)
//
// Manifest arity:
// - positions: ${posCount}
// - totalCandidates: ${totalCandidates}
//
// Candidate counts are provided per position as counts_<i>[] signals,
// plus abstain[] per position.
//
// Public inputs:
//   electionIdHash, electionVoteRoot, manifestHash, resultsHash
//
// Private inputs:
//   abstain[], counts_<i>[]
//
pragma circom 2.1.6;

include "circomlib/poseidon.circom";

template BVTallyResultCommitV1() {
  // Public anchors
  signal input electionIdHash;
  signal input electionVoteRoot;
  signal input manifestHash;
  signal input resultsHash;

  // Private tally vector
  signal input abstain[${posCount}];
`;

  let countsDecl = "";
  for (let i = 0; i < posCount; i++) {
    countsDecl += `  signal input counts_${i}[${candCountsPerPos[i]}];\n`;
  }

  const hashInit = `
  // Poseidon fold hash
  component p0 = Poseidon(2);
  p0.inputs[0] <== ${domainConst};
  p0.inputs[1] <== electionIdHash;

  component p1 = Poseidon(2);
  p1.inputs[0] <== p0.out;
  p1.inputs[1] <== electionVoteRoot;

  component p2 = Poseidon(2);
  p2.inputs[0] <== p1.out;
  p2.inputs[1] <== manifestHash;

  signal h;
  h <== p2.out;
`;

  let fold = "";
  let poseIdx = 3;

  for (let i = 0; i < posCount; i++) {
    fold += `
  component p${poseIdx} = Poseidon(2);
  p${poseIdx}.inputs[0] <== h;
  p${poseIdx}.inputs[1] <== abstain[${i}];
  h <== p${poseIdx}.out;
`;
    poseIdx += 1;

    for (let j = 0; j < candCountsPerPos[i]; j++) {
      fold += `
  component p${poseIdx} = Poseidon(2);
  p${poseIdx}.inputs[0] <== h;
  p${poseIdx}.inputs[1] <== counts_${i}[${j}];
  h <== p${poseIdx}.out;
`;
      poseIdx += 1;
    }
  }

  const footer = `
  // Bind to claimed resultsHash
  h === resultsHash;
}

component main = BVTallyResultCommitV1();
`;

  return header + countsDecl + hashInit + fold + footer;
}

function parseArgs(argv: string[]) {
  const args: Record<string, string | boolean> = {};
  for (let i = 2; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--electionId") {
      args.electionId = argv[++i];
    } else if (a === "--manifestFile") {
      args.manifestFile = argv[++i];
    } else if (a === "--outCircom") {
      args.outCircom = argv[++i];
    } else if (a === "--outMeta") {
      args.outMeta = argv[++i];
    } else if (a === "--help" || a === "-h") {
      args.help = true;
    }
  }
  return args;
}

async function main() {
  const args = parseArgs(process.argv);
  if (args.help) {
    console.log("Usage:");
    console.log("  node zk/scripts/generate-tally-circuit.ts --electionId <uuid>");
    console.log("  node zk/scripts/generate-tally-circuit.ts --manifestFile <path>");
    console.log("Optional:");
    console.log("  --outCircom zk/circuits/tally.circom");
    console.log("  --outMeta   zk/circuits/tally.meta.json");
    process.exit(0);
  }

  const outCircom = (args.outCircom as string) ?? path.join("zk", "circuits", "tally.circom");
  const outMeta = (args.outMeta as string) ?? path.join("zk", "circuits", "tally.meta.json");

  let manifestObj: unknown;

  if (args.electionId) {
    const row = await fetchElectionManifest(args.electionId as string);
    const snapPath = writeManifestSnapshot(row, path.join("zk", "manifests"));
    console.log(`Using Supabase manifest. Snapshot: ${snapPath}`);
    manifestObj = readJson(snapPath);
  } else if (args.manifestFile) {
    manifestObj = readJson(args.manifestFile as string);
  } else {
    console.error("Missing --electionId or --manifestFile. Use --help for usage.");
    process.exit(1);
  }

  // Accept either a snapshot envelope or raw manifest JSON
  const env = manifestObj as SnapshotEnvelope;
  const rawManifest =
    env && typeof env === "object" && "manifest" in env && env.manifest
      ? (env.manifest as Manifest)
      : (manifestObj as Manifest);

  const positions = normalizePositions(rawManifest);

  const meta = { positions };
  const circom = emitCircom(meta);

  fs.mkdirSync(path.dirname(outCircom), { recursive: true });
  fs.writeFileSync(outCircom, circom, "utf8");
  fs.writeFileSync(outMeta, JSON.stringify(meta, null, 2), "utf8");

  console.log(`Generated: ${outCircom}`);
  console.log(`Meta:      ${outMeta}`);
}

if (require.main === module) {
  main().catch((e) => {
    console.error(String(e));
    process.exit(1);
  });
}
