#!/usr/bin/env node
/**
 * zk/scripts/generate-tally-circuit.ts
 *
 * Generates zk/circuits/tally.circom from an election manifest JSON.
 *
 * DESIGN (Step 2.5 scope):
 * - Produces a **deterministic results commitment gadget** bound to:
 *     electionIdHash, electionVoteRoot, manifestHash, resultsHash
 * - Uses Poseidon folding hash inside the circuit so we don't need Keccak-in-circuit.
 * - This circuit is the "Results Commitment" layer. The next step composes it with the
 *   vote-set binding layer (root binding) using an agreed ZK-friendly root commitment path.
 *
 * Manifest expectations:
 * - manifest.positions: array
 *   Each position item may be:
 *     - string (position name), OR
 *     - { name: string, candidates: any[] }
 * - For candidates, we only need counts length per position:
 *     - position.candidates.length
 *
 * Output:
 * - zk/circuits/tally.circom
 * - zk/circuits/tally.meta.json (position/candidate arity used for codegen)
 */

import fs from "node:fs";
import path from "node:path";

type ManifestPosition =
  | string
  | {
      name?: string;
      position?: string;
      candidates?: unknown[];
    };

type Manifest = {
  spec_version?: string;
  positions?: ManifestPosition[];
  // allow nesting if your manifest is { manifest: {...} }
  manifest?: {
    positions?: ManifestPosition[];
    spec_version?: string;
  };
};

function readJson(filePath: string): unknown {
  return JSON.parse(fs.readFileSync(filePath, "utf8"));
}

function normalizePositions(manifestRaw: Manifest): { name: string; candidateCount: number }[] {
  const inner = (manifestRaw.manifest ?? manifestRaw) as Manifest;
  const positions = inner.positions ?? [];
  if (!Array.isArray(positions) || positions.length === 0) {
    throw new Error("Manifest missing positions[]");
  }

  return positions.map((p, idx) => {
    if (typeof p === "string") {
      return { name: p, candidateCount: 0 }; // candidate arity unknown; caller should use object form
    }
    const name = (p.name ?? p.position ?? `Position_${idx}`) as string;
    const candidateCount = Array.isArray(p.candidates) ? p.candidates.length : 0;
    return { name, candidateCount };
  });
}

/**
 * Poseidon folding hash:
 *   h0 = Poseidon([domain, electionIdHash])
 *   h1 = Poseidon([h0, electionVoteRoot])
 *   h2 = Poseidon([h1, manifestHash])
 *   then fold each count:
 *     h = Poseidon([h, count_i])
 *   finally constrain h == resultsHash
 *
 * NOTE: This binds the results vector to the 3 anchors + domain separator.
 */
function emitCircom(meta: { positions: { name: string; candidateCount: number }[] }) {
  // Flatten candidate counts + abstain per position
  const posCount = meta.positions.length;
  const candCountsPerPos = meta.positions.map((p) => p.candidateCount);

  const totalCandidates = candCountsPerPos.reduce((a, b) => a + b, 0);

  const domainConst = "123456789"; // BV_TALLY_RESULT_V1 domain separator (field element)
  // We'll keep it as a constant field element; you can rotate it in future spec versions.

  const header = `// AUTOGENERATED by zk/scripts/generate-tally-circuit.ts
// Output: zk/circuits/tally.circom
// Purpose: Results commitment gadget (BV_TALLY_RESULT_COMMIT_V1)
//
// IMPORTANT:
// - This circuit DOES NOT (yet) prove that counts come from the vote-set leaves.
//   It proves that a claimed results vector is bound to (electionIdHash, electionVoteRoot, manifestHash).
// - Next step composes this with vote-set binding in a ZK-friendly way.
//
// Manifest arity:
// - positions: ${posCount}
// - totalCandidates: ${totalCandidates}
//
// Candidate counts are provided as a 2D array [positions][candidateCount(pos)] and abstain[] per position.
//
// Public inputs:
//   electionIdHash, electionVoteRoot, manifestHash, resultsHash
//
// Private inputs:
//   counts[][], abstain[]
//
pragma circom 2.1.6;

include "circomlib/poseidon.circom";

template BVTallyResultCommitV1() {
  // Public anchors
  signal input electionIdHash;
  signal input electionVoteRoot;
  signal input manifestHash;
  signal input resultsHash;

  // Private tally vector
  signal input abstain[${posCount}];
`;

  let countsDecl = "";
  for (let i = 0; i < posCount; i++) {
    countsDecl += `  signal input counts_${i}[${candCountsPerPos[i]}];
`;
  }

  const hashInit = `
  // Poseidon fold hash
  component p0 = Poseidon(2);
  p0.inputs[0] <== ${domainConst};
  p0.inputs[1] <== electionIdHash;

  component p1 = Poseidon(2);
  p1.inputs[0] <== p0.out;
  p1.inputs[1] <== electionVoteRoot;

  component p2 = Poseidon(2);
  p2.inputs[0] <== p1.out;
  p2.inputs[1] <== manifestHash;

  signal h;
  h <== p2.out;
`;

  let fold = "";
  let poseIdx = 3;
  // Fold abstain first per position, then counts
  for (let i = 0; i < posCount; i++) {
    fold += `
  component p${poseIdx} = Poseidon(2);
  p${poseIdx}.inputs[0] <== h;
  p${poseIdx}.inputs[1] <== abstain[${i}];
  h <== p${poseIdx}.out;
`;
    poseIdx += 1;

    for (let j = 0; j < candCountsPerPos[i]; j++) {
      fold += `
  component p${poseIdx} = Poseidon(2);
  p${poseIdx}.inputs[0] <== h;
  p${poseIdx}.inputs[1] <== counts_${i}[${j}];
  h <== p${poseIdx}.out;
`;
      poseIdx += 1;
    }
  }

  const footer = `
  // Bind to claimed resultsHash
  h === resultsHash;
}

component main = BVTallyResultCommitV1();
`;

  return header + countsDecl + hashInit + fold + footer;
}

function main() {
  const manifestPath = process.argv[2];
  const outCircom = process.argv[3] ?? path.join("zk", "circuits", "tally.circom");
  const outMeta = process.argv[4] ?? path.join("zk", "circuits", "tally.meta.json");

  if (!manifestPath) {
    console.error("Usage: generate-tally-circuit <manifest.json> [outCircom] [outMeta]");
    process.exit(1);
  }

  const manifestRaw = readJson(manifestPath) as Manifest;
  const positions = normalizePositions(manifestRaw);

  // Guard: if candidateCount is zero for any position, circuit will still compile,
  // but you likely want candidates[] present in manifest for those positions.
  const meta = { positions };

  const circom = emitCircom(meta);

  fs.mkdirSync(path.dirname(outCircom), { recursive: true });
  fs.writeFileSync(outCircom, circom, "utf8");
  fs.writeFileSync(outMeta, JSON.stringify(meta, null, 2), "utf8");

  console.log(`Generated: ${outCircom}`);
  console.log(`Meta:      ${outMeta}`);
}

main();
